authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
import mainapp.views as mainapp
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   re_path(r'^$', mainapp.products, name='index'),
   re_path(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
   re_path(r'^category/(?P<pk>\d+)/ajax/$',
           cache_page(3600)(mainapp.products_ajax)),
   re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),

   re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', 
           mainapp.products, name='page'),
   re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/ajax/$',
           cache_page(3600)(mainapp.products_ajax)),
]

mainapp/models.py
from django.db import models

# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='кол-во товара', default=0)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

class MenuCategory(models.Model):
    name = models.CharField(verbose_name='имя категории', max_length=64, unique=True)
    desc = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return f"{self.name}"

mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
import os
from basketapp.models import Basket
from geekshop.settings import BASE_DIR
from django.template.loader import render_to_string
from django.views.decorators.cache import cache_page
from django.http import JsonResponse
import json
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.views.decorators.cache import never_cache

from .management.commands.fill_db import JSON_PATH
from .models import ProductCategory, Product, MenuCategory

# Create your views here.

def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)

def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)
    
def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category') 
    
def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)

def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')     

def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_ordered_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True,  category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True,  category__is_active=True).order_by('price')    


def get_hot_product():
    products = get_products().order_by('?').first()
    return products


def get_same_products(hot_product):
    if hot_product is None:
        return None
    else:
        same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
        return same_products


def main(request):
    title = 'главная'
    products = get_products()[:3]
    content = {
        'title': title,
        'products': products,
    }

    return render(request, 'mainapp/index.html', content)


def contact(request):
    title = 'контакты'
    content = {
        'title': title,
    }
    return render(request, 'mainapp/contact.html', content)


@never_cache
def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = get_links_menu()

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = get_products_ordered_by_price()
        else:
            category = get_category(pk)
            products = get_products_in_category_ordered_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/products.html', content)

@never_cache
def product(request, pk):
    title = 'продукты'
 
    content = {
        'title': title,
        'links_menu': get_links_menu(),
        'product': get_product(pk),
    }

    return render(request, 'mainapp/product.html', content)


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', errors='ignore') as infile:
        return json.load(infile)

def products_ajax(request, pk=None, page=1):
    if request.is_ajax():
        links_menu = get_links_menu()

        if pk:
            if pk == '0':
                category = {
                    'pk': 0,
                    'name': 'все'
                }
                products = get_products_ordered_by_price()
            else:
                category = get_category(pk)
                products = get_products_in_category_ordered_by_price(pk)
 
            paginator = Paginator(products, 2)
            try:
                products_paginator = paginator.page(page)
            except PageNotAnInteger:
                products_paginator = paginator.page(1)
            except EmptyPage:
                products_paginator = paginator.page(paginator.num_pages)
 
            content = {
                'links_menu': links_menu,
                'category': category,
                'products': products_paginator,
            }
 
            result = render_to_string(
                         'mainapp/includes/inc_products_list_content.html',
                         context=content,
                        request=request)
 
            return JsonResponse({'result': result})

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>
       {% block title %}
           {{ title|capfirst }}
       {% endblock %}
   </title>
   {% block css %}
       <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
       <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
   {% endblock %}
   {% block js %}
       <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
       <script src="{% static 'js/bootstrap.min.js' %}"></script>
       <script src="{% static 'js/main_scripts.js' %}"></script>
   {% endblock %}
</head>
<body>
<div class="container">
    {% block menu %}

    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
        <div class="footer">
            <div class="clearfix">
                <div class="text-footer">
                    <h3>контакты</h3>
                </div>
                <div class="text-footer">
                    <h3>полезная информация</h3>
                </div>
                <div class="text-footer clearfix">
                    <h3>Оставайтесь на связи</h3>
                    <p>Подписаться на новости и рассылки</p>
                    <form>
                        <input type="email" name="email" placeholder="ваш email">
                        <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                    </form>
                </div>
            </div>
            <p class="small">&copy; GB {% now "Y" %}</p>
            <div class="social">
                <a href="#" class="social1"></a>
                <a href="#" class="social2"></a>
                <a href="#" class="social3"></a>
                <a href="#" class="social4"></a>
            </div>
            <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
        </div>
    {% endblock %}
</div>

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
    <div class="hero">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
        <h1>наши контакты</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="location">
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
    </div>

    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
    <div class="slider">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static "img/arrow.png"%}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="featured">
        <div class="featured-menu">
                <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static "img/arrow.png"%}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for item in products %}
                <div class="block">
                    <a href="{% url 'products:product' item.pk %}"><img src="/media/{{ item.image }}" alt="{{ item.short_desc }}">
                        <div class="text">
                            <img src="{% static "img/icon-hover.png"%}" alt="/static/img">
                            <h4>{{ item.category.name }}</h4>
                            <h3>{{ item.name }}</h3>
                            <p>{{ item.description }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>
    <div class="clr"></div>
{% endblock %}



mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
    </div>
{% endblock %}
{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}" 
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать 
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ hot_product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price">{{ hot_product.price }} <span>руб</span></p>
                <a href="{% url 'products:product' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ hot_product.description }}
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h3>Категория:{{ product.category.name }}</h3>
                                <h4>Название: {{ product.name }}</h4>
                                <p>Описание: {{ product.description }} </p>
                                <p>Цена: {{ product.price }} </p>
                                <p>На складе: {{ product.quantity }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
   <div class="details">
       {% include 'mainapp/includes/inc_products_list_content.html' %}
   </div>

   <div class="clr"></div>
{% endblock %}